using Microsoft.Extensions.Logging;

namespace DataAssetBackend.Features.Assets;

/// <summary>
/// Server-side policy for generating/normalizing identifiers for the Copy Asset flow.
/// </summary>
/// <remarks>
/// Contract:
/// - Purpose:
///   - Ensure copy operations do not reuse identifiers that must be globally unique in the DB,
///     even if the client accidentally sends duplicates.
/// - Inputs:
///   - A <see cref="CopyAssetRequest"/> where <see cref="CopyAssetRequest.TargetAsset"/> is present.
/// - Outputs:
///   - The same request instance with guaranteed-safe IDs for copy (mutated in-place).
/// - Invariants:
///   - <c>TargetAsset.GlobalUniqueAssetId</c> is always a fresh value generated by the server.
///   - <c>TargetAsset.PermitEuId</c> is always a fresh value generated by the server.
/// - Errors:
///   - None (best-effort generation; relies on GUID uniqueness).
/// - Side effects:
///   - Mutates the request's <see cref="CopyAssetTargetAsset"/> fields.
/// Observability:
///   - Logs what was overridden (without leaking secrets).
/// </remarks>
public static class AssetCopyIdPolicy
{
    // PUBLIC_INTERFACE
    /// <summary>
    /// Applies server-side copy ID generation to ensure DB uniqueness constraints are not violated.
    /// </summary>
    public static void ApplyServerGeneratedIdsForCopy(CopyAssetRequest request, ILogger logger)
    {
        // Always generate fresh IDs for copy to enforce "new asset" semantics server-side.
        // We do not attempt a DB "check then insert" loop here; GUID collision risk is negligible.
        var newGlobalUniqueAssetId = $"guaid-{Guid.NewGuid():N}";
        var newPermitEuId = $"permit-copy-{Guid.NewGuid():N}";

        var oldGlobal = request.TargetAsset.GlobalUniqueAssetId;
        var oldPermit = request.TargetAsset.PermitEuId;

        request.TargetAsset.GlobalUniqueAssetId = newGlobalUniqueAssetId;
        request.TargetAsset.PermitEuId = newPermitEuId;

        // Log only that we overrode values, not the full originals (avoid propagating client mistakes).
        logger.LogInformation(
            "AssetCopyIdPolicy applied server-generated IDs for copy. overridden_global_unique_asset_id={OverrodeGlobal}, overridden_permit_eu_id={OverrodePermit}",
            !string.IsNullOrWhiteSpace(oldGlobal),
            !string.IsNullOrWhiteSpace(oldPermit));
    }
}
